#!/usr/bin/env bash
# Keep `zig build` linkable against the installed macOS SDKs.
#
# The macOS 26 SDK ships usr/lib/libSystem.B.tbd with only an arm64e-macos
# slice; the plain arm64-macos slice is gone. Zig 0.15.2 (the version ghostty
# pins) matches tbd slices exactly, so -lSystem resolves to nothing and every
# libc symbol comes back undefined. That breaks Zig's own build runner, so
# `zig build` fails before a build script even runs.
#
# Zig asks `xcrun --show-sdk-path` where the SDK is, so pointing that answer at
# the newest installed SDK that still carries an arm64-macos slice is enough.
# The shim is a no-op once the active SDK works, so it disappears on its own
# when Zig or the SDK catches up.

# libSystem.B.tbd is a multi-document file: the first document describes the
# umbrella libSystem itself and the rest describe its reexports. Only the
# umbrella's slices decide whether -lSystem resolves, and the reexports still
# list arm64-macos on SDKs where the umbrella has dropped it, so a whole-file
# match reports a false pass.
zig_darwin_sdk_slice_ok() {
  local tbd="$1/usr/lib/libSystem.B.tbd"
  [[ -f "$tbd" ]] || return 1
  awk '/^--- !tapi-tbd/ { doc++ } doc == 1' "$tbd" | grep -q 'arm64-macos'
}

zig_darwin_sdk_find_compatible() {
  local candidate
  while IFS= read -r candidate; do
    [[ -d "$candidate" ]] || continue
    if zig_darwin_sdk_slice_ok "$candidate"; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done < <(
    ls -d \
      /Library/Developer/CommandLineTools/SDKs/MacOSX*.sdk \
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX*.sdk \
      2>/dev/null | sort -rV
  )
  return 1
}

# Exports a PATH entry that overrides `xcrun` when, and only when, the active
# SDK cannot satisfy a Zig link. Returns non-zero if no usable SDK exists.
zig_darwin_sdk_setup() {
  [[ "$(uname -s)" == "Darwin" ]] || return 0
  [[ "$(uname -m)" == "arm64" ]] || return 0

  local active
  active="$(xcrun --show-sdk-path 2>/dev/null || true)"
  if [[ -n "$active" ]] && zig_darwin_sdk_slice_ok "$active"; then
    return 0
  fi

  local sdk
  if ! sdk="$(zig_darwin_sdk_find_compatible)"; then
    echo "error: the active macOS SDK has no arm64-macos slice in libSystem.B.tbd" >&2
    echo "       and no installed SDK does either, so Zig cannot link." >&2
    echo "       Install Command Line Tools that carry an older SDK, or upgrade" >&2
    echo "       ghostty to a Zig release that accepts arm64e-only slices." >&2
    return 1
  fi

  local bin="${CMUX_ZIG_SDK_SHIM_DIR:-$HOME/.cache/cmux/zig-sdk-shim}/bin"
  mkdir -p "$bin"
  local version
  version="$(basename "$sdk" | sed -e 's/^MacOSX//' -e 's/\.sdk$//')"
  cat > "$bin/xcrun" <<EOF
#!/bin/sh
# Generated by scripts/lib/zig-darwin-sdk.sh — do not edit.
#
# Answer only bare macOS SDK-path queries, which is all Zig asks. Anything
# naming a tool (ranlib, metal, clang) or another platform's SDK must reach the
# real xcrun untouched, or the iOS slices of a universal build break.
want_path=0
want_version=0
named_sdk=""
named_tool=0
expect_sdk=0
for arg in "\$@"; do
  if [ "\$expect_sdk" = 1 ]; then named_sdk="\$arg"; expect_sdk=0; continue; fi
  case "\$arg" in
    --show-sdk-path) want_path=1 ;;
    --show-sdk-version) want_version=1 ;;
    --sdk|-sdk) expect_sdk=1 ;;
    --sdk=*) named_sdk="\${arg#--sdk=}" ;;
    -*) ;;
    *) named_tool=1 ;;
  esac
done
case "\$named_sdk" in
  ""|macosx*) ;;
  *) exec /usr/bin/xcrun "\$@" ;;
esac
if [ "\$named_tool" = 0 ] && [ "\$want_path" = 1 ]; then echo "$sdk"; exit 0; fi
if [ "\$named_tool" = 0 ] && [ "\$want_version" = 1 ]; then echo "$version"; exit 0; fi
exec /usr/bin/xcrun "\$@"
EOF
  chmod +x "$bin/xcrun"
  export PATH="$bin:$PATH"

  echo "==> Zig: active SDK lacks an arm64-macos slice; linking against $(basename "$sdk")"
}
